<?php

namespace BlogBundle\Repository;

use BlogBundle\Entity\Tag;
use Doctrine\ORM\EntityRepository;

/**
 * ArticleTagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleTagsRepository extends EntityRepository
{

    public function searchArticlesByTag(Tag $tag)
    {
        try {
            $articles = $this
                ->createQueryBuilder('p')
                ->where('p.tagId = :id')
                ->setParameter('id', $tag)
                ->getQuery()
                ->getArrayResult()
                ;
            print_r($articles);
            // ->getOneOrNullResult() équivalent au getSingleResult()
            return $articles;
        } catch (\Exception $ex) {
//            print_r($ex);
//            return null;
            throw new \Exception($ex);
        }
    }
}
