<?php

namespace BlogBundle\Repository;

use BlogBundle\Entity\Tag;
use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function searchByName($search)
    {
        try {
            $tag = $this
                ->createQueryBuilder('p')
                ->where('p.name = :name')
                ->setParameter('name', $search)
                ->getQuery()
                ->getOneOrNullResult();

            return $tag;
        } catch (\Exception $ex) {
            throw new \Exception($ex);
        }
    }

    public function getArticles($search)
    {
        try {
            $tag = $this
                ->createQueryBuilder('p')
                ->where('p.name = :name')
                ->setParameter('name', $search)
                ->getQuery()
                ->getOneOrNullResult();
            if($tag) {
                return $tag->getArticles();
            } else {
                return null;
            }
        } catch (\Exception $ex) {
            throw new \Exception($ex);
        }
    }
}
