services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    blog.search:
        class: BlogBundle\Services\SearchManager
        arguments: [@doctrine]

    blog.comment:
        class: BlogBundle\Services\CommentManager
        arguments: [@doctrine]

    blog.pagination:
        class: BlogBundle\Services\PaginationManager
        arguments: [@doctrine]

    blog.cookie_listener:
        class: BlogBundle\Listener\CookieListener
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: checkCookies}