BlogBundle\Entity\ArticleTags:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\ArticleTagsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        articleId:
            targetEntity: Article
            joinColumn:
              name: article_id
              referencedColumnName: id
              nullable: false
        tagId:
            targetEntity: Tag
            joinColumn:
              name: tag_id
              referencedColumnName: id
              nullable: false
    lifecycleCallbacks: {  }
